

MANUAL_ALIASES = {
    # --- High Profile Name Alignments & Fixes ---
    'erling haaland': 'erling braut haland',
    'gabriel': 'gabriel dos santos magalhaes',
    'rodri': 'rodrigo hernandez cascante',
    'pedri': 'pedro gonzalez lopez',
    'antony': 'antony matheus dos santos',
    'savio': 'savio moreira de oliveira',
    'gavi': 'pablo martin paez gavira',
    'pablo': 'pablo martin paez gavira',
    'rodrygo': 'rodrygo silva de goes',
    'raphinha': 'raphael dias belloli',
    'endrick': 'endrick felipe moreira de sousa',
    'casemiro': 'carlos henrique casimiro',
    'bernardo': 'bernardo mota veiga de carvalho e silva',
    'ederson': 'ederson jose dos santos lourenco da silva',
    'vitinha': 'vitor manuel carvalho oliveira',
    'koke': 'jorge resurreccion merodio',
    'evanilson': "francisco evanilson de lima barbosa",

    # --- Consolidated Core Corrections (e.g., Max Weiss Fix) ---
    'max weiss': 'max weiss',
    'max wei': 'max weiss',
    'djordje petrovic': 'or_e petrovic', 
    'aaron': 'aaron wan-bissaka',
    'mat ryan': 'mathew david ryan',
    'marc guehi': 'addji keaninkin marc-israel guehi',
    'odisseas vlachodimos': 'odysseas vlachodimos',

    # --- Premier League Dimensions ---
    'ollie watkins': 'oliver george arthur watkins',
    'chris richards': 'christopher jeffrey richards',
    'alex iwobi': 'alexander chuka iwobi',
    'nick pope': 'nicholas david pope',
    'dan burn': 'daniel johnson burn',
    'dan ballard': 'daniel george ballard',
    'phil foden': 'philip walter foden',
    'djed spence': 'diop tehuti djed-hotep spence',
    'joelinton': 'joelinton cassio apolinario de lira',
    'ben chilwell': 'benjamin james chilwell',
    'will hughes': 'william james hughes',
    'max kilman': 'maximilian william kilman',
    'tim iroegbunam': 'timothy emeka iroegbunam',
    'tosin adarabioyo': 'abdul-nasir tosin adarabioyo',
    'tom cairney': 'thomas cairney',
    'ben white': 'benjamin william white',
    'josh acheampong': 'joshua kofi acheampong',
    'cj egan-riley': 'conrad jaden egan-riley',
    'eddie nketiah': 'edward keddar nketiah',
    'tyler dibling': 'tyler-jay robert dibling',
    'dominic solanke': 'dominic ayodele solanke',
    'joe willock': 'joseph george willock',
    'chris wood': 'christopher grant wood',
    'sam johnstone': 'samuel luke johnstone',
    'adam armstrong': 'adam james armstrong',
    'andy robertson': 'andrew henry robertson',
    'joe rodon': 'joseph peter rodon',
    'noni madueke': 'chukwunonso tristan madueke',
    'freddie woodman': 'frederick john woodman',
    'tammy abraham': 'tammy abraham',

    # --- La Liga Dimensions ---
    'remiro': 'alejandro remiro gargallo',
    'alex moreno': 'alexandre moreno lopera',
    'alex grimaldo': 'alejandro grimaldo garcia',
    'dani vivian': 'daniel vivian moreno',
    'nico paz': 'nicolas paz martinez',
    'samu costa': 'samuel de almeida costa',
    'yuri': 'yuri berchiche izeta',
    'pep chavarria': 'josep maria chavarria perez',
    'edu exposito': 'eduardo exposito jaen',
    'nacho vidal': 'ignacio vidal miralles',
    'isi palazon': 'isaac palazon camacho',
    'abde ezzalzouli': 'abdessamad ezzalzouli',
    'alex berenguer': 'alejandro berenguer remiro',
    'yeremi pino': 'yeremy jesus pino santos',
    'dani olmo': 'daniel olmo carvajal',
    'raillo': 'antonio jose raillo arenas',
    'juanlu sanchez': 'juan luis sanchez velasco',
    'rafa marin': 'rafael marin zamora',
    'alex balde': 'alejandro balde martinez',
    'rafa mir': 'rafael mir vicente',
    'javi galan': 'javier galan gil',
    'copete': 'jose manuel arias copete',
    'nico williams': 'nicholas williams arthuer',
    'kike garcia': 'enrique garcia martinez',
    'raul': 'raul de tomas gomez',
    'dani calvo': 'daniel calvo san roman',
    'alex baena': 'alejandro baena rodriguez',
    'nico gonzalez': 'nicolas gonzalez iglesias',
    'fran beltran': 'francisco jose beltran peinado',
    'abde rebbach': 'abderrahman rebbach',
    'abdel abqar': 'abdelkabir abqar',
    'inaki pena': 'ignacio pena sotorres',
    'roberto navarro': 'robert navarro munoz',
    'fran perez': 'francisco perez martinez',
    'moi gomez': 'moises gomez bordonado',
    'rafael obrador': 'rafael obrador burguera',
    'javi puado': 'javier puado diaz',
    'raul moro': 'raul moro prescoli',
    'toni lato': 'antonio latorre grueso',
    'alvaro fidalgo': 'alvaro fidalgo fernandez',
    'javi munoz': 'javier munoz jimenez',
    'josan': 'jose antonio ferrandez pomares',
    'yeray alvarez': 'yeray alvarez lopez',
    'sergi roberto': 'sergi roberto carnicer',
    'portu': 'cristian portugues manzanera',
    'dani ceballos': 'daniel ceballos fernandez',
    'morales': 'jose luis morales nogales',
    'isco': 'francisco roman alarcon suarez',
    'raba': 'daniel raba antolin',
    'kike salas': 'enrique salas valiente',
    'fran garcia': 'francisco jose garcia torres',

    # --- Bundesliga Dimensions ---
    'ferdi kadioglu': 'ferdi erenay kadoglu',
    'waldemar anton': 'waldemar anton', 
    'willi orban': 'vilmos tamas orban',
    'frederik ronnow': 'frederik riis rnnow',
    'yannick engelhardt': 'yannik engelhardt',
    'joshua vagnoman': 'josha mamadou karaboue vagnoman',
    'joakim maehle': 'joakim mhle pedersen',
    'karim adeyemi': 'karim-david adeyemi',
    'wout faes': 'wout faes',
    'max rosenfelder': 'maximilian rosenfelder',
    'damion downs': 'damion downs',

    # --- Serie A Dimensions ---
    'fikayo tomori': 'oluwafikayomi oluwadamilola tomori',
    'kenan yildiz': 'kenan yldz',
    'bremer': 'gleison bremer silva nascimento',
    'marcus thuram': 'marcus lilian thuram-ulien',
    'enrico del prato': 'enrico delprato',
    'ruslan malinovskiy': 'ruslan malinovskyi',
    'milan djuric': 'milan uric',
    'lucas paqueta': 'lucas tolentino coelho de lima',
    'franck zambo': 'andre-frank zambo anguissa',
    'michael gregoritsch': 'michael gregoritsch',
    'patric': 'patricio gabarron gil',

    # --- Ligue 1 Dimensions ---
    'adrien rabiot': 'adrien rabiot-provost',
    'cristian casseres jr.': 'cristian sleiker casseres yepes',
    'kephren thuram': 'khephren thuram-ulien',
    'abner': 'abner vinicius da silva santos',
    'alexis claude maurice': 'alexis claude-maurice',
    'pierre ganiou': 'pierre-ismaelo ganiou',
    'william pacho': 'willian joel pacho tenorio',
    'mohamed ali-cho': 'mohamed-ali cho',
    'beraldo': 'lucas lopes beraldo',
    'jean-daniel akpa-akpro': 'jean-daniel dave lewis akpa akpro',
    'm\'bala nzola': 'mbala n\'zola',
    'remy cabella': 'remy cabella',
    'lucas gourna douath': 'lucas gourna-douath',
    'przemyslaw frankowski': 'przemysaw frankowski',
    'emanuel emegha': 'emmanuel esseh emegha',
    'stanley n\'soki': 'stanley pierre nsoki',
    'wesley': 'wesley fofana',

    # --- Eredivisie, Rest of World & Emerging Prospects ---
    'danny namaso': 'danny loader', 
    'alisson': 'alisson ramses becker',
    'albert gudmundsson': 'albert gumundsson',
    'danny welbeck': 'danielii welbeck',
    'tasos douvikas': 'anastasios douvikas',
    'yehor yarmolyuk': 'yehor yarmoliuk',
    'yann gboho': 'yann gboho',
    'joe scally': 'joseph michael scally',
    'ilaix moriba': 'moriba kourouma kourouma',
    'giorgi tsitaishvili': 'georgiy tsitaishvili',
    'mohammed amoura': 'mohamed amoura',
    'otavio': 'otavio edmilson da silva monteiro',
    'marnon busch': 'marnon-thomas busch',
    'azz-eddine ounahi': 'azzedine ounahi',
    'xavi simons': 'xavier quentin shay simons',
    'hichem boudaoui': 'hicham boudaoui',
    'omari hutchinson': 'omari elijah giraud-hutchinson',
    'lukasz skorupski': 'ukasz skorupski',
    'josh cullen': 'joshua jon cullen',
    'kenneth taylor': 'kenneth taylor',
    'naif aguerd': 'nayef aguerd',
    'justin bijlow': 'justin bijlow',
    'tolu arokodare': 'toluwalase emmanuel arokodare',
    'armel bella kotchap': 'armel bella-kotchap',
    'martin odegaard': 'martin degaard',
    'saud abdulhamid': 'saud abdullah abdul hamid',
    'darline yongwa': 'darlin zidane yongwa ngameni',
    'branco van den boomen': 'branco van den boomen',
    'pape diop': 'pape demba diop',
    'quinten timber': 'quinten timber',
    'mohammed salisu': 'mohammed salisu',
    'estupinan': 'pervis josue estupinan tenorio',
    'nicolas fonseca': 'nicolas fonseca',
    'semih kilicsoy': 'semih klcsoy',
    'cheick tidiane sabaly': 'cheikh tidiane sabaly',
    'omri gandelman': 'omri gandelman',
    'tani oluwaseyi': 'tanitoluwa oluwatimikhin oluwaseyi',
    'youssef el-arabi': 'youssef el arabi',
    'joao cancelo': 'joao pedro cavaco cancelo',
    'abdou harroui': 'abdoulrahmane harroui',
    'johnny cardoso': 'joao lucas de souza cardoso',
    'sulemana': 'kamaldeen sulemana',
    'fode toure': 'fode ballo-toure',
    'estevao': 'estevao willian almeida',
    'ibrahima sissoko': 'ibrahima sissoko',
    'sebastian szymanski': 'sebastian szymanski',
    'chris rigg': 'christopher john rigg',
    'obed vargas': 'obed vargas',
    'matt o\'riley': 'matthew sean o\'riley',
    'gonzalo villar': 'gonzalo villar del fraile',
    'mathias rasmussen': 'mathias klinge rasmussen',
    'nicolas kuhn': 'nicolas-gerrit kuhn',
    'rodrigo ribeiro': 'rodrigo ribeiro',
    'jones el abdellaoui': 'jones el-abdellaoui',
    'vanderson': 'vanderson de oliveira campos',
    'roman yaremchuk': 'roman yaremchuk',
    'altay bayindir': 'altay bayndr',
    'noah nartey': 'noah nartey',
    'marius louar': 'marius louer',
    'hugo bolin': 'hugo bolin',
    'zito': 'zito andre sebastiao luvumbo',
    'philip otele': 'philip otele',
    'giorgi kvilitaia': 'giorgi kvilitaia',
    'jan ziolkowski': 'jan ziokowski',
    'konan ndri': 'konan ndri',
    'maxi oyedele': 'maximillian oyedele',
    'allan saint-maximin': 'allan saint-maximin',
    'filip jorgensen': 'filip jrgensen',
    'jesper lindstrom': 'jesper grnge lindstrm',
    'silas wamangituka': 'silas katompa mvumpa',
    'lionel mpasi': 'lionel m\'pasi n\'zau',
    'hong hyun-seok': 'hyeon-seok hong',
    'manu bueno': 'manuel bueno sebastian',
    'pedro lima': 'pedro lima',
    'arthur masuaku': 'fuka-arthur masuaku kawela',
    'dodi lukebakio': 'dodi lukebakio',
    'andy irving': 'andrew irving',
    'david datro fofana': 'david datro fofana',
}